/* Datos */

insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Veal - Kidney', '29.94');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Energy Drink - Franks Pineapple', '7.02');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Savory', '64.69');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'White Fish - Filets', '11.90');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Tahini Paste', '95.55');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Beans - Turtle, Black, Dry', '36.72');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Compound - Pear', '43.04');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Garlic - Peeled', '48.15');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Pepper - Julienne, Frozen', '84.93');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Cup - 3.5oz, Foam', '34.53');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Vinegar - Sherry', '22.26');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Cotton Wet Mop 16 Oz', '47.21');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Carroway Seed', '47.24');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Table Cloth 54x54 Colour', '6.66');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Wine - Delicato Merlot', '66.20');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Red Snapper - Fillet, Skin On', '88.46');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Milk - 1%', '88.46');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Foam Cup 6 Oz', '40.12');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Capon - Whole', '14.03');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Dr. Pepper - 355ml', '93.07');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Tart Shells - Savory, 2', '63.15');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Coffee - Cafe Moreno', '35.73');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Nut - Hazelnut, Whole', '35.15');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Oil - Grapeseed Oil', '0.29');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Pastry - Carrot Muffin - Mini', '63.40');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Ham - Cooked', '48.49');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Apples - Sliced / Wedge', '90.13');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Tea - Vanilla Chai', '0.69');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Cheese - Camembert', '32.77');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Arrowroot', '1.77');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'French Pastry - Mini Chocolate', '28.83');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Bread Sour Rolls', '8.25');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Chick Peas - Canned', '33.79');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Vacuum Bags 12x16', '81.35');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Muffin Mix - Lemon Cranberry', '83.55');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Sauce - Demi Glace', '50.68');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Tart Shells - Barquettes, Savory', '82.68');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Wine - Sauvignon Blanc', '37.97');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Bagel - Sesame Seed Presliced', '42.66');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Wine - Mas Chicet Rose, Vintage', '63.07');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Currants', '64.11');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Sambuca Cream', '27.52');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Nut - Pine Nuts, Whole', '81.64');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Fork - Plastic', '5.44');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Bagel - Plain', '90.44');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Beer - Steamwhistle', '39.86');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Beans - Black Bean, Canned', '59.37');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Coconut - Whole', '72.66');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Pasta - Shells, Medium, Dry', '1.96');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Beets', '74.18');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Oil - Olive Bertolli', '55.16');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Bagel - Everything', '96.69');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Mangoes', '50.79');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Syrup - Monin - Granny Smith', '80.37');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Pork Loin Cutlets', '88.12');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Oven Mitts 17 Inch', '37.29');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Pail - 4l White, With Handle', '41.86');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Wine - Touraine Azay - Le - Rideau', '92.01');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Pants Custom Dry Clean', '90.22');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Bread - Roll, Canadian Dinner', '41.23');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Beef - Tongue, Fresh', '23.34');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Sea Bass - Fillets', '43.97');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Chef Hat 20cm', '78.79');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Artichoke - Fresh', '15.90');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Anchovy Fillets', '28.75');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Beef - Tenderloin - Aa', '20.94');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Pork - Back, Long Cut, Boneless', '63.80');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Lid - 16 Oz And 32 Oz', '85.11');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Snapple Lemon Tea', '16.41');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Lemonade - Natural, 591 Ml', '89.61');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Bag Clear 10 Lb', '81.66');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Crush - Cream Soda', '55.72');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Tea - Herbal Sweet Dreams', '21.59');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Bay Leaf', '76.05');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Salad Dressing', '75.42');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Lettuce - Radicchio', '81.72');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Onion - Dried', '98.70');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Chocolate Liqueur - Godet White', '50.90');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Milk - Skim', '66.89');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Carbonated Water - Wildberry', '89.78');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Energy - Boo - Koo', '56.37');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Curry Paste - Green Masala', '71.86');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Carbonated Water - Lemon Lime', '5.06');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Coriander - Ground', '99.73');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Paste - Black Olive', '46.60');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Ecolab - Hobart Upr Prewash Arm', '81.34');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Pasta - Lasagne, Fresh', '5.97');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Beer - True North Strong Ale', '81.61');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Wine - Red, Cooking', '18.69');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Stock - Beef, Brown', '97.14');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Cranberries - Dry', '38.44');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Tarts Assorted', '11.68');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Salt And Pepper Mix - White', '21.09');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Lobak', '28.67');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Pate - Liver', '52.78');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Apple - Macintosh', '87.30');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Nantucket - 518ml', '22.99');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Gatorade - Fruit Punch', '36.61');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Bread - French Baquette', '56.96');
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Rambutan', '86.57');